spring:
  datasource:
    url: jdbc:oracle:thin:@${ORACLE_HOST:192.168.1.205}:${ORACLE_PORT:5566}:arltr
    username: lark_search
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    druid:
      max-active: 18
      initial-size: 3
      min-idle: 3
      max-wait: 250000
      time-between-eviction-runs-millis: 250000
      min-evictable-idle-time-millis: 120000
      validation-query: select 'x' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      max-open-prepared-statements: 20
      filter: stat,wall,log4j

