
package com.github.hollykunge.serviceunitproject.serviceimpl.servicebiz;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "synchrodataPortType", targetNamespace = "http://impl.webservice.dev.casic.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SynchrodataPortType {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getProjectData")
    @WebResult(targetNamespace = "http://impl.webservice.dev.casic.com")
    @RequestWrapper(localName = "getProjectData", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.GetProjectData")
    @ResponseWrapper(localName = "getProjectDataResponse", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.GetProjectDataResponse")
    public String getProjectData();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getAllTeamData")
    @WebResult(targetNamespace = "http://impl.webservice.dev.casic.com")
    @RequestWrapper(localName = "getAllTeamData", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.GetAllTeamData")
    @ResponseWrapper(localName = "getAllTeamDataResponse", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.GetAllTeamDataResponse")
    public String getAllTeamData();

    /**
     * 
     * @param xmlStr
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getPatOrgDataService")
    @WebResult(targetNamespace = "http://impl.webservice.dev.casic.com")
    @RequestWrapper(localName = "getPatOrgDataService", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.GetPatOrgDataService")
    @ResponseWrapper(localName = "getPatOrgDataServiceResponse", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.GetPatOrgDataServiceResponse")
    public String getPatOrgDataService(
            @WebParam(name = "xmlStr", targetNamespace = "http://impl.webservice.dev.casic.com")
                    String xmlStr);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getDocPackage")
    @WebResult(targetNamespace = "http://impl.webservice.dev.casic.com")
    @RequestWrapper(localName = "getDocPackage", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.GetDocPackage")
    @ResponseWrapper(localName = "getDocPackageResponse", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.GetDocPackageResponse")
    public String getDocPackage();

    /**
     * 
     * @param xmlStr
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getTechModelListService")
    @WebResult(targetNamespace = "http://impl.webservice.dev.casic.com")
    @RequestWrapper(localName = "getTechModelListService", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.GetTechModelListService")
    @ResponseWrapper(localName = "getTechModelListServiceResponse", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.GetTechModelListServiceResponse")
    public String getTechModelListService(
            @WebParam(name = "xmlStr", targetNamespace = "http://impl.webservice.dev.casic.com")
                    String xmlStr);

    /**
     * 
     * @param xmlStr
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getTechDataListService")
    @WebResult(targetNamespace = "http://impl.webservice.dev.casic.com")
    @RequestWrapper(localName = "getTechDataListService", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.GetTechDataListService")
    @ResponseWrapper(localName = "getTechDataListServiceResponse", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.GetTechDataListServiceResponse")
    public String getTechDataListService(
            @WebParam(name = "xmlStr", targetNamespace = "http://impl.webservice.dev.casic.com")
                    String xmlStr);

    /**
     * 
     * @param isContain
     * @param unitId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getUsersByUnitId")
    @WebResult(targetNamespace = "http://impl.webservice.dev.casic.com")
    @RequestWrapper(localName = "getUsersByUnitId", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.GetUsersByUnitId")
    @ResponseWrapper(localName = "getUsersByUnitIdResponse", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.GetUsersByUnitIdResponse")
    public String getUsersByUnitId(
            @WebParam(name = "unitId", targetNamespace = "http://impl.webservice.dev.casic.com")
                    String unitId,
            @WebParam(name = "isContain", targetNamespace = "http://impl.webservice.dev.casic.com")
                    String isContain);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getAllProjectData")
    @WebResult(targetNamespace = "http://impl.webservice.dev.casic.com")
    @RequestWrapper(localName = "getAllProjectData", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.GetAllProjectData")
    @ResponseWrapper(localName = "getAllProjectDataResponse", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.GetAllProjectDataResponse")
    public String getAllProjectData();

    /**
     * 
     * @param xmlStr
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getTechDocListService")
    @WebResult(targetNamespace = "http://impl.webservice.dev.casic.com")
    @RequestWrapper(localName = "getTechDocListService", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.GetTechDocListService")
    @ResponseWrapper(localName = "getTechDocListServiceResponse", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.GetTechDocListServiceResponse")
    public String getTechDocListService(
            @WebParam(name = "xmlStr", targetNamespace = "http://impl.webservice.dev.casic.com")
                    String xmlStr);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getAllTemp")
    @WebResult(targetNamespace = "http://impl.webservice.dev.casic.com")
    @RequestWrapper(localName = "getAllTemp", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.GetAllTemp")
    @ResponseWrapper(localName = "getAllTempResponse", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.GetAllTempResponse")
    public String getAllTemp();

    /**
     * 
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getUserPosition")
    @WebResult(targetNamespace = "http://impl.webservice.dev.casic.com")
    @RequestWrapper(localName = "getUserPosition", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.GetUserPosition")
    @ResponseWrapper(localName = "getUserPositionResponse", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.GetUserPositionResponse")
    public String getUserPosition(
            @WebParam(name = "userId", targetNamespace = "http://impl.webservice.dev.casic.com")
                    String userId);

    /**
     * 
     * @param projectId
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getProjectDataByProjectId")
    @WebResult(targetNamespace = "http://impl.webservice.dev.casic.com")
    @RequestWrapper(localName = "getProjectDataByProjectId", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.GetProjectDataByProjectId")
    @ResponseWrapper(localName = "getProjectDataByProjectIdResponse", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.GetProjectDataByProjectIdResponse")
    public String getProjectDataByProjectId(
            @WebParam(name = "projectId", targetNamespace = "http://impl.webservice.dev.casic.com")
                    String projectId,
            @WebParam(name = "userId", targetNamespace = "http://impl.webservice.dev.casic.com")
                    String userId);

    /**
     * 
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getAllProjectByUserId")
    @WebResult(targetNamespace = "http://impl.webservice.dev.casic.com")
    @RequestWrapper(localName = "getAllProjectByUserId", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.GetAllProjectByUserId")
    @ResponseWrapper(localName = "getAllProjectByUserIdResponse", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.GetAllProjectByUserIdResponse")
    public String getAllProjectByUserId(
            @WebParam(name = "userId", targetNamespace = "http://impl.webservice.dev.casic.com")
                    String userId);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getTechdocList")
    @WebResult(targetNamespace = "http://impl.webservice.dev.casic.com")
    @RequestWrapper(localName = "getTechdocList", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.GetTechdocList")
    @ResponseWrapper(localName = "getTechdocListResponse", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.GetTechdocListResponse")
    public String getTechdocList();

    /**
     * 
     * @param xmlStr
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:syncDataService")
    @WebResult(targetNamespace = "http://impl.webservice.dev.casic.com")
    @RequestWrapper(localName = "syncDataService", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.SyncDataService")
    @ResponseWrapper(localName = "syncDataServiceResponse", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.SyncDataServiceResponse")
    public String syncDataService(
            @WebParam(name = "xmlStr", targetNamespace = "http://impl.webservice.dev.casic.com")
                    String xmlStr);

    /**
     * 
     * @param xmlStr
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:syncProjectDataService")
    @WebResult(targetNamespace = "http://impl.webservice.dev.casic.com")
    @RequestWrapper(localName = "syncProjectDataService", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.SyncProjectDataService")
    @ResponseWrapper(localName = "syncProjectDataServiceResponse", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.SyncProjectDataServiceResponse")
    public String syncProjectDataService(
            @WebParam(name = "xmlStr", targetNamespace = "http://impl.webservice.dev.casic.com")
                    String xmlStr);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getPackageDocRef")
    @WebResult(targetNamespace = "http://impl.webservice.dev.casic.com")
    @RequestWrapper(localName = "getPackageDocRef", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.GetPackageDocRef")
    @ResponseWrapper(localName = "getPackageDocRefResponse", targetNamespace = "http://impl.webservice.dev.casic.com", className = "com.casic.dev.webservice.impl.GetPackageDocRefResponse")
    public String getPackageDocRef();

}
